# NAME: selfproxy
# AUTHOR: kjxing
# REPO: https://github.com/blackmatrix7/ios_rule_script
# UPDATED: 2024-07-03 16:16:17
# DOMAIN-SUFFIX: 259
# TOTAL: 259
payload:
  - DOMAIN-SUFFIX,bing.com
  - DOMAIN-SUFFIX,110329.xyz
  - DOMAIN-SUFFIX,linkedin.com
  - DOMAIN-SUFFIX,810903.xyz
  - DOMAIN,copilot.cloud.microsoft
